package ProfilePage;

public enum Department {
    MECHANICAL,
    CIVIL,
    ECE,
    EEE,
    AUTO_MOBILE,
    CHEMICAL,
    MECHATRONICS,
    BIOTECHNOLOGY,
    BIOMEDICAL,
    FOOD_TECHNOLOGY,
    COMPUTER_SCIENCE,
    INFORMATION_TECHNOLOGY;
}
